[package]
name = "rscan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scanner = { path = "scanner" }
tokio = { version = "1", features = ["full"]}
tracing = "0.1"
tracing-subscriber = "0.3"

[workspace]
members = [".", "scanner"]
