[package]
name = "command-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
rlimit = "0.9"
serde = { version = "1", features = ["derive"]}
anyhow = "1.0.71"
serde_json = "1"
